// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urukdcuubogfqwkipccr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVydWtkY3V1Ym9nZnF3a2lwY2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjU1MTUsImV4cCI6MjA2MTIwMTUxNX0.56ImDFI4GP0NG6mZxh3_jgp7H9fA0xw0tSKRVNhIJqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);